config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  resources :items
  devise_for :users
  resources :join_table_items_carts, only: [:create, :update, :destroy]
  resources :carts, except: [:index, :new, :edit]
  resources :orders, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_items_carts, dependent: :nullify
end

app/models/item.rb
class Item < ApplicationRecord   
    has_many :join_table_items_carts, dependent: :nullify

    validates :title, presence: true, length: { minimum: 3, maximum: 20}
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :price, presence: true, :inclusion => { in: 1..1000, message: "Prix entre 1 et 1000" }
    validates :image_url, presence: true
end

app/models/join_table_items_cart.rb
class JoinTableItemsCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def self.add_or_create_cart_item_link(permit_link_params)
  	if JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id]) == nil
  		@new_item_add = JoinTableItemsCart.create(item_id: permit_link_params[:item_id], cart_id: permit_link_params[:cart_id], quantity: 1)
  	else
  		@new_item_add = JoinTableItemsCart.find_by(cart_id: permit_link_params[:cart_id], item_id: permit_link_params[:item_id])
  		@new_item_add.update(quantity: @new_item_add.quantity + 1)
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
    after_action :create_cart_and_assign_to_current_user, only: [:create]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  before_action :require_login
  before_action :only_current_cart
  def show
    @items_in_cart = JoinTableItemsCart.where(cart_id:current_user.cart.id)
  end

  def update
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ItemsHelper
  before_action :save_items_in_cart
  before_action :set_item, only: %i[ show edit update destroy ]

  def index
    @items = Item.all
    @join_table_item_cart = JoinTableItemsCart.new
  end

  def show
    @items = Item.find(params[:id])
    @join_table_item_cart = JoinTableItemsCart.new
    # Use callbacks to share common setup or constraints between actions.
  end
  private
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {})
    end
end

app/controllers/join_table_items_carts_controller.rb
class JoinTableItemsCartsController < ApplicationController
  def create
    @item_add = JoinTableItemsCart.add_or_create_cart_item_link(permit_link_params)
    redirect_to items_path
  end

  def update
  end

  def destroy
    @item_delete = JoinTableItemsCart.find(params[:id])
    @item_delete.destroy
    redirect_to cart_path
  end

  private

  def permit_link_params
    params.require(:join_table_items_cart).permit(:item_id, :cart_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ItemsHelper
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
    @stripe_amount = 500
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_path
    end
    #UserMailer.order
    # After the rescue, if the payment succeeded
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def create_cart_and_assign_to_current_user
        if current_user != nil && current_user.cart == nil
            cart = Cart.create(user: current_user)
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
    private

    def require_login
        unless current_user != nil
            redirect_to new_user_session_path
        end
    end

    def only_current_cart
        if current_user != nil && current_user.cart.id != params[:id].to_i
            return redirect_to cart_path(current_user.cart.id)
        end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
    def save_items_in_cart
        if current_user != nil
            @items_in_cart = JoinTableItemsCart.where(cart_id:current_user.cart.id)
        end
    end
end

app/helpers/join_table_items_carts_helper.rb
module JoinTableItemsCartsHelper
    
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/show.html.erb
<br/>
<div class="container">
    <h1>Mon panier</h1>
    <br/>
    <br/>
        <div class="row">
            <div class="col-lg-8 col-md-8">
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Quantité</th>
                        <th scope="col">Nom de produit</th>
                        <th scope="col">Prix unitaire</th>
                        <th scope="col">Prix selon quantité</th>
                        <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        <% total_price = [] %>
                        <%  @items_in_cart.each do |item| %>
                        <tr>
                            <th scope="row"><%= item.quantity %></th>
                            <td><%= item.item.title %></td>
                            <td><%= item.item.price %>€</td>
                            <td><%= total_item = item.item.price*item.quantity.to_d %>€</td>
                            <td>
                                <div class="btn-group me-2" role="group" aria-label="First group">
                                    <button type="button" class="btn btn-outline-warning">-</button>
                                    <button type="button" class="btn btn-outline-warning">+</button>
                                </div>
                            </td>
                            <td><a href="<%= join_table_items_cart_path(item.id) %>" class="btn btn-danger" data-confirm="Êtes-vous sûr de vouloir supprimer ce-t-s article-s du panier ?" data-method="DELETE">Supprimer l'article</a></td>
                            <% total_price << total_item %>
                        </tr>
                        <% end %>
                         <tr>
                            <th scope="row"></th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr class=" table-light">
                            <th scope="row"></th>
                            <td></td>
                            <td class="bold">Prix total:</td>
                            <td><%= total_price.inject(0){|sum,x| sum + x }%>€</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <%=link_to 'Passer la commande', new_order_path, class: 'btn btn-primary'%>
        </div>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="px-4 pt-2 mb-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">Photos de chatons</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Le meilleur et le seul site d'achat de photos de chatons qui existe. Que cela soit pour vous ou pour offrir découvrez ici tout les meilleurs cliché de petits chats prit par des photographes professionels et imprimé par nos soins.</p>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
      <div class="container px-5">
        <%= image_tag "cat-image-1.jpg", size: "700x500", class: "img-fluid border rounded-3 shadow-lg mb-4" %>
      </div>
    </div>
</div>
  <body>
    <div class="row">
        <% @items.each do |item| %>
        <div class="col-sm-3">
          <div class="card" style="margin: 20px;">
          <div class="card-body">
            <img src="<%= item.image_url %>" alt="random cat" width="700" height="500" class="img-fluid border rounded-3 shadow-lg mb-4">
            <a href="<%= item_path(item.id) %>" class="card-link"><h5 class="card-title"><%= item.title %></h5></a>
            <p class="card-text"><%=item.description%></p>

              <div class="row">
              <div class="col">
                <span class="btn btn-outline-secondary"><%= item.price %> €</span>
              </div>
              <div class="col">
              <% if user_signed_in? %>
                <%= form_for @join_table_item_cart do |f| %>
                    <%= f.hidden_field :item_id, value: item.id %>
                    <%= f.hidden_field :cart_id, value: current_user.cart.id %>
                    <button type="submit" class="btn btn-success">Ajouter au panier</button>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
          </div>
        </div>
        <% end %>
    </div>
  </body>
<br>
<footer class="footer mt-auto py-3 text-center bg-light">
        <div class="row">
          <div class="col-lg-12">
            <p>Made by <a href="https://github.com/T-PRAT">Titouan Prat</a>.</p>
            <p>Based on <a href="https://getbootstrap.com/" rel="nofollow">Bootstrap</a> and <a href="https://bootswatch.com/minty/">bootswatch minty theme</a></p>
          </div>
        </div>
 </footer>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5 border-bottom">
  <div class="row">
    <div class="col-md">
      <img src="<%= @item.image_url %>" alt="random cat" width="700" height="500" class="img-fluid border rounded-3 shadow-lg mb-4">
    </div>
    <div class="col-md">
      <h2><%= @item.title %></h2>
      <p><%= @item.description %></p>
      <h3><%= @item.price %> €</h3>
      <% if user_signed_in? %>
          <%= form_for @join_table_item_cart do |f| %>
              <%= f.hidden_field :item_id, value: @item.id %>
              <%= f.hidden_field :cart_id, value: current_user.cart.id %>
              <button type="submit" class="btn btn-success">Ajouter au panier</button>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi omnis doloribus veritatis, reprehenderit rerum, amet eius perferendis iste numquam non quis doloremque magni, modi perspiciatis illum distinctio sequi quidem minus!</p>
    </div>
    <div class="col-md-6">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Chamazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-primary fixed-top">
      <div class="container-fluid">
    <%= link_to 'Chamazon', root_path, class: "navbar-brand ms-5" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Accueil', root_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mr-0">
      <% if current_user %>
                <% if @items_in_cart && @items_in_cart.count > 0 %>
                  <% total_items = []
                      @items_in_cart.each do |item_choosed|
                          item_quantity = item_choosed.quantity
                          total_items << item_quantity
                      end %>
                <li class="nav-item me-3">
                  <%= link_to "Se déconnecter", destroy_user_session_path, class: 'btn btn-outline-danger btn-sm', method: "DELETE" %>
                </li>
                <li class="nav-item">
                  <%= link_to cart_path(current_user.cart.id) do %>
                    <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.iconsdb.com%2Ficons%2Fpreview%2Fwhite%2Fcart-xxl.png&f=1&nofb=1", size: "30x30" %>
                  <% end %>
                </li>
                    <span class="badge"><%= total_items.inject(0){|sum,x| sum + x }%></span>
                <% else %>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to "Se déconnecter", destroy_user_session_path, class: 'btn btn-outline-danger btn-sm', method: "DELETE" %>
                </li>
                  <%= link_to cart_path(current_user.cart.id) do %>
                    <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.iconsdb.com%2Ficons%2Fpreview%2Fwhite%2Fcart-xxl.png&f=1&nofb=1", size: "30x30" %>
                  <% end %>
                <% end %>
        <% else %>
            <li class="nav-item me-3"><%= link_to 'Se connecter', new_user_session_path, class: 'btn btn-outline-light' %></li>
            <li class="nav-item"><%= link_to "Créer un compte", new_user_registration_path, class: 'btn btn-light' %></li>
      <%end%>
      </ul>
    </div>
    </div>
    </nav>
    <main style="margin-top: 80px;">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<%= form_tag orders_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="500"
    data-locale="auto">
</script>
<% end %>